services:
  # Postgres with pgvector extension
  db-postgres:
    image: pgvector/pgvector:pg17
    container_name: aris-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Neo4j Graph Database
  db-neo4j:
    image: neo4j:5.18.0
    container_name: aris-neo4j
    restart: always
    ports:
      - "7474:7474" # HTTP Console
      - "7687:7687" # Bolt Protocol
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs: